ALTER TABLE member ADD email varchar(256) DEFAULT NULL;
ALTER TABLE member ADD id_card varchar(64) DEFAULT NULL;
ALTER TABLE member ADD address varchar(256) DEFAULT NULL;
ALTER TABLE member ADD DATA DATE DEFAULT NULL;

