spring:
  application:
    name: player
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: service
      password: OnePiece123!@#
      url: jdbc:mysql://94.237.76.206:3306/onepiece?useUnicode=true&characterEncoding=UTF-8
  profiles:
    active: dev

server:
  servlet:
    context-path: /api/v1/player